CREATE TABLE IF NOT EXISTS user_roles (
    id INT UNIQUE AUTO_INCREMENT,
    user_id INT,
    role_id INT,
    is_active BOOLEAN NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
)