CREATE TABLE IF NOT EXISTS scores (
    id INT UNIQUE AUTO_INCREMENT,
    user_id VARCHAR(30) NOT NULL,
    score INT,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
)